
#include "masterConf.h"


byte electricalLinesPins[] = {
	POUT_RELAY_WATER, 
	POUT_RELAY_FRIDGE, 
	POUT_RELAY_HEATING, 
	POUT_RELAY_AUX, 
	POUT_RELAY_SPARE, 
	POUT_RELAY_LIGHT
};

DeviceAddress TempProbes[] = {
	/* Sensor #0 */ {0x28,0x94,0x13,0xFB,0x5,0x0,0x0,0x91 }, 		//	TEMP_FRIDGE
	/* Sensor #1 */ {0x28,0x1C,0x73,0xDA,0x2,0x0,0x0,0x4E }, 		//	TEMP_INSIDE_1
	/* Sensor #2 */ {0x28,0x59,0x85,0xDA,0x2,0x0,0x0,0xEA },		//	TEMP_INSIDE_2 
	/* Sensor #3 */ {0x28,0x79,0x87,0xDA,0x2,0x0,0x0,0xDF },		//	TEMP_WATER_PRIMARY 
	/* Sensor #4 */ {0x28,0x15,0x58,0xC4,0x3,0x0,0x0,0xD6 }, 		//	TEMP_WATER_SECONDARY
	/* Sensor #5 */ {0x28,0x93,0xB1,0x9C,0x4,0x0,0x0,0x19 }, 		//	TEMP_HEAT_BLOWER
	/* Sensor #6 */ {0x28,0x53,0xEB,0x9C,0x4,0x0,0x0,0xAE }			//	TEMP_OUTSIDE
};

byte lightsConf[][9] = {
	{PINT_LIGHT_SWITCH_1,	LIGHT_TYPE_NORMAL, 		POUT_LIGHT_SSD_1, 	0, 					0,					0,	0,	0,	0	},
	{PINT_LIGHT_SWITCH_2,	LIGHT_TYPE_NORMAL, 		POUT_LIGHT_SSD_2, 	0, 					0,					0,	0,	0,	0	},
	{PINT_LIGHT_SWITCH_3,	LIGHT_TYPE_RGB_DIMMABLE, 	POUT_LIGHT_RGB_1_R, 	POUT_LIGHT_RGB_1_G, 	POUT_LIGHT_RGB_1_B,	0,	0,	0,	0	}
};

Button* inputSwitchs[NB_INPUT_SWITCHS] ;


float currentCalFactors[] = {
	CURRENT_FACTOR_COLD_MODULE,
	CURRENT_FACTOR_WATER_MODULE,
	CURRENT_FACTOR_HEAT_MODULE,
	CURRENT_FACTOR_LIGHT_MODULE,
	CURRENT_FACTOR_AUX_MODULE,
	CURRENT_FACTOR_SPARE_MODULE,
	CURRENT_FACTOR_SOLAR_GENE
};

short currents[NB_CURRENT_SENSORS];

byte currentPins[] = {
	PIN_CURRENT_COLD_MODULE,
	PIN_CURRENT_WATER_MODULE,
	PIN_CURRENT_HEAT_MODULE,
	PIN_CURRENT_LIGHT_MODULE,
	PIN_CURRENT_AUX_MODULE,
	PIN_CURRENT_SPARE_MODULE,
	PIN_CURRENT_SOLAR_GENE
};

float tensionCalFactors[] = {
	TENSION_FACTOR_BATT_PRIM,
	TENSION_FACTOR_BATT_AUX
};

byte tensionPins[] = {
	PIN_TENSION_BATT_PRIM,
	PIN_TENSION_BATT_AUX
};

short tensions[NB_TENSION_SENSORS];

boolean needHeaterOn;

